name: Test

on:
  push:
    branches: [main, issue-*]
  pull_request:
    branches: [main, issue-*]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: "3.9"

      - name: Setup Poetry
        run: pip3 install poetry

      - name: Check Poetry
        run: poetry --version

      - name: Config Poetry for Cache
        if: ${{ !env.ACT }}
        run: poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        if: ${{ !env.ACT }}
        uses: actions/cache@v2.1.6
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-v0-${{ github.event.repository.name }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install via Poetry
        run: poetry install

      - name: Run Pytest Test
        run: poetry run pytest --cov
